In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv(r'C:\Users\SHYAM SASHANK\OneDrive\Desktop\Data_Science\Assginment_CSV\Company_Data.csv')

In [3]:
df

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,Good,33,14,Yes,Yes
396,6.14,139,23,3,37,120,Medium,55,11,No,Yes
397,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes
398,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes
399,9.71,134,37,0,27,120,Good,49,16,Yes,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64
 2   Income       400 non-null    int64
 3   Advertising  400 non-null    int64
 4   Population   400 non-null    int64
 5   Price        400 non-null    int64
 6   ShelveLoc    400 non-null    object
 7   Age          400 non-null    int64
 8   Education    400 non-null    int64
 9   Urban        400 non-null    object
 10  US           400 non-null    object
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
labelencoder= LabelEncoder()

df["ShelveLoc"]=labelencoder.fit_transform(df["ShelveLoc"])

df["Urban"]=labelencoder.fit_transform(df["Urban"])

df["US"]=labelencoder.fit_transform(df["US"])

In [7]:
df

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,0,42,17,1,1
1,11.22,111,48,16,260,83,1,65,10,1,1
2,10.06,113,35,10,269,80,2,59,12,1,1
3,7.40,117,100,4,466,97,2,55,14,1,1
4,4.15,141,64,3,340,128,0,38,13,1,0
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,1,33,14,1,1
396,6.14,139,23,3,37,120,2,55,11,0,1
397,7.41,162,26,12,368,159,2,40,18,1,1
398,5.94,100,79,7,284,95,0,50,12,1,1
399,9.71,134,37,0,27,120,1,49,16,1,1

In [8]:
X=df.drop(columns="Sales")
X.head()

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,138,73,11,276,120,0,42,17,1,1
1,111,48,16,260,83,1,65,10,1,1
2,113,35,10,269,80,2,59,12,1,1
3,117,100,4,466,97,2,55,14,1,1
4,141,64,3,340,128,0,38,13,1,0

In [9]:
Y=df[["Sales"]]
Y.head()

   Sales
0   9.50
1  11.22
2  10.06
3   7.40
4   4.15

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=20)

In [12]:
X_train

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
268,123,57,0,66,105,2,39,11,1,0
108,107,79,2,488,103,0,65,16,1,0
21,134,29,12,239,109,1,62,18,0,1
231,132,69,0,123,122,2,27,11,0,0
33,114,38,13,317,128,1,50,16,1,1
...,...,...,...,...,...,...,...,...,...,...
393,109,51,10,26,120,2,30,17,0,1
218,138,61,12,156,120,2,25,14,1,1
223,110,45,9,276,125,2,62,14,1,1
271,111,56,0,504,110,2,62,16,1,0
355,130,100,0,306,146,1,42,11,1,0

In [13]:
X_test

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
10,121,78,9,150,100,0,26,10,0,1
382,121,28,19,315,121,2,66,14,1,1
374,131,47,7,90,118,2,47,12,1,1
196,130,28,6,410,133,0,72,16,1,1
47,126,98,0,173,108,0,55,16,1,0
...,...,...,...,...,...,...,...,...,...,...
147,140,54,9,402,119,1,41,16,0,1
375,132,46,4,206,124,2,73,11,1,0
113,131,29,11,335,127,0,33,12,1,1
291,118,70,0,106,89,0,39,17,1,0
172,104,102,13,123,110,1,35,16,1,1

In [14]:
Y_train

     Sales
268   6.53
108   3.47
21   12.13
231   8.09
33    8.77
..     ...
393   5.57
218   9.70
223   3.45
271   4.55
355   7.02

[280 rows x 1 columns]

In [15]:
Y_test

     Sales
10    9.01
382   4.95
374   9.44
196   4.10
47    4.38
..     ...
147  10.51
375   7.90
113   6.01
291   6.64
172   9.03

[120 rows x 1 columns]

In [16]:
y_train=labelencoder.fit_transform(Y_train)
y_train
y_test= labelencoder.fit_transform(Y_test)
print(y_test)

[ 81  26  88  12  16  91  59  54  72  84  34  99  87  36  30  60   5 108
 105  28  23  58  52  19   8 104  41 109  86 111   0  24  93  73  79  89
  27  80 110  57  35  62  38  63  85  77  44  71  57  37 101  75  10  95
  83  96  74  56 113  78  11  13  21  48  19 103  64  15  83  39  65  92
 106   7   1  29  40  20  35   6  69  25  68 102  18 107  22  58  31  90
  49  70 100  43  76   3  46  53 112  14   9  32  55  60  61  17   4  66
   2  98  33  50  47  94  45  97  67  42  51  82]

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

In [18]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [19]:
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [20]:
y_pred_train=model.predict(X_train)
y_pred_train

array([ 92,  14, 232, 144, 169,   6, 226, 134, 235, 161, 167, 103, 155,
        81,  70, 204, 159,  65, 129, 158, 173, 115, 190,  47,  53, 226,
        73,  97, 199,  94, 102, 156, 237, 169, 237,  58, 165,  10, 216,
       174, 210,  11,  62,  21, 118,  74, 191,  39, 245, 108, 238,  52,
       186,  98, 208, 119,  58, 211, 135, 142,  43, 116, 157, 206,  12,
       219, 126, 223, 192,  56, 220,  61,  28, 207,  69, 172, 219,  27,
       141,  78,  37, 194,  44, 114, 222, 166, 100,   3,  15, 104, 154,
       234, 163, 135,  29, 148,  79,  17,   9,  36,  45,  80,  88, 122,
       203, 183, 229,  89, 146,  38, 137,  99, 198, 141, 212, 176, 106,
         0,  95, 150,  71,  19, 123, 188,  83, 223, 175,  22,  48,  24,
        31,  30,  55,  40, 101, 177, 128, 152, 231,  86,  84, 121, 189,
       103, 125, 136, 184,  20, 244,  42, 164, 162, 233, 113,  93, 242,
        46,   1, 112, 108,  91, 139,  75, 151, 196,  83, 131, 218,   2,
       140,  34, 135, 182, 221, 213,  35, 195, 182, 230,  82,  72,   7,
       160,  73, 130,  76,  40,  23, 138, 215, 143,  57, 239, 214, 118,
        73, 228, 170,  97,  67, 105,  51, 227, 236,  91, 146, 247, 217,
       225, 147, 197, 181, 149, 185, 202,  32, 153,  92, 107, 209,  54,
        26, 120,  48,  41, 187, 117, 205, 168, 182,   8, 127,  97, 248,
        63, 157,  79, 180, 201,  20,  25,  60,  49, 111,  59,  85, 179,
       109,  77, 224,  87,   4,  23, 246,  92, 145,  96, 130, 133, 243,
        64, 178, 171, 240,  50,  68, 241,  18, 132,   5, 124,  16,  90,
       111, 200,  66, 193,  13,  33, 110], dtype=int64)

In [21]:
y_pred_test=model.predict(X_test)
y_pred_test

array([ 23, 182,  36, 131,  31, 125, 201,  89,  92, 108,  36, 194, 206,
       114, 114,  40,  79, 190, 130, 174,  40,  37,   7, 174,  55, 141,
       114, 191, 116, 102,  97,   4, 141, 215, 162, 204, 126, 176, 181,
        70, 137, 146, 157,  71, 212, 135, 182, 163,  95,  91,  97,  68,
        98, 104, 188, 237,  52,  78, 103, 156, 132,  46,  23,  91,  78,
       228, 241,  73,  41,  23,  35, 248, 158,  55,   1,  92,  64,  26,
       120,  99, 197,   3,  23,  64, 210, 160,  29,  44,  10, 226,  99,
       135, 169, 139, 104,  17, 209,  18, 180,   8,  46, 157, 169, 116,
        79,  49,   4,  62,  47, 221, 133,  48,  83,  95, 190, 219,  52,
       107,  69, 135], dtype=int64)

In [22]:
from sklearn.metrics import classification_report

In [23]:
print(classification_report(y_pred_test,y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      1.00      1.00         1
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         1
           4       1.00      0.50      0.67         2
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         0
          17       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         0
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         0
          23       0.00      0.00      0.00         4
          24       0.00      0.00      0.00         0
          25       0.00      0.00      0.00         0
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         0
          28       0.00      0.00      0.00         0
          29       0.00      0.00      0.00         1
          30       0.00      0.00      0.00         0
          31       0.00      0.00      0.00         1
          32       0.00      0.00      0.00         0
          33       0.00      0.00      0.00         0
          34       0.00      0.00      0.00         0
          35       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         2
          37       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         0
          39       0.00      0.00      0.00         0
          40       0.00      0.00      0.00         2
          41       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         0
          43       0.00      0.00      0.00         0
          44       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         0
          46       0.00      0.00      0.00         2
          47       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         1
          49       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         0
          51       0.00      0.00      0.00         0
          52       0.00      0.00      0.00         2
          53       0.00      0.00      0.00         0
          54       0.00      0.00      0.00         0
          55       0.00      0.00      0.00         2
          56       0.00      0.00      0.00         0
          57       0.00      0.00      0.00         0
          58       0.00      0.00      0.00         0
          59       0.00      0.00      0.00         0
          60       0.00      0.00      0.00         0
          61       0.00      0.00      0.00         0
          62       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         0
          64       0.00      0.00      0.00         2
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         0
          67       0.00      0.00      0.00         0
          68       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         1
          70       0.00      0.00      0.00         1
          71       0.00      0.00      0.00         1
          72       0.00      0.00      0.00         0
          73       0.00      0.00      0.00         1
          74       0.00      0.00      0.00         0
          75       0.00      0.00      0.00         0
          76       0.00      0.00      0.00         0
          77       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         2
          79       0.00      0.00      0.00         2
          80       0.00      0.00      0.00         0
          81       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         0
          83       0.00      0.00      0.00         1
          84       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         0
          86       0.00      0.00      0.00         0
          87       0.00      0.00      0.00         0
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         2
          92       0.00      0.00      0.00         2
          93       0.00      0.00      0.00         0
          94       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         2
          96       0.00      0.00      0.00         0
          97       0.00      0.00      0.00         2
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         2
         100       0.00      0.00      0.00         0
         101       0.00      0.00      0.00         0
         102       0.00      0.00      0.00         1
         103       0.00      0.00      0.00         1
         104       0.00      0.00      0.00         2
         105       0.00      0.00      0.00         0
         106       0.00      0.00      0.00         0
         107       0.00      0.00      0.00         1
         108       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         0
         110       0.00      0.00      0.00         0
         111       0.00      0.00      0.00         0
         112       0.00      0.00      0.00         0
         113       0.00      0.00      0.00         0
         114       0.00      0.00      0.00         3
         116       0.00      0.00      0.00         2
         120       0.00      0.00      0.00         1
         125       0.00      0.00      0.00         1
         126       0.00      0.00      0.00         1
         130       0.00      0.00      0.00         1
         131       0.00      0.00      0.00         1
         132       0.00      0.00      0.00         1
         133       0.00      0.00      0.00         1
         135       0.00      0.00      0.00         3
         137       0.00      0.00      0.00         1
         139       0.00      0.00      0.00         1
         141       0.00      0.00      0.00         2
         146       0.00      0.00      0.00         1
         156       0.00      0.00      0.00         1
         157       0.00      0.00      0.00         2
         158       0.00      0.00      0.00         1
         160       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         1
         163       0.00      0.00      0.00         1
         169       0.00      0.00      0.00         2
         174       0.00      0.00      0.00         2
         176       0.00      0.00      0.00         1
         180       0.00      0.00      0.00         1
         181       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         2
         188       0.00      0.00      0.00         1
         190       0.00      0.00      0.00         2
         191       0.00      0.00      0.00         1
         194       0.00      0.00      0.00         1
         197       0.00      0.00      0.00         1
         201       0.00      0.00      0.00         1
         204       0.00      0.00      0.00         1
         206       0.00      0.00      0.00         1
         209       0.00      0.00      0.00         1
         210       0.00      0.00      0.00         1
         212       0.00      0.00      0.00         1
         215       0.00      0.00      0.00         1
         219       0.00      0.00      0.00         1
         221       0.00      0.00      0.00         1
         226       0.00      0.00      0.00         1
         228       0.00      0.00      0.00         1
         237       0.00      0.00      0.00         1
         241       0.00      0.00      0.00         1
         248       0.00      0.00      0.00         1

    accuracy                           0.02       120
   macro avg       0.01      0.01      0.01       120
weighted avg       0.03      0.02      0.02       120

In [24]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_train, y_pred_train))

Accuracy: 1.0

In [25]:
from sklearn.metrics import confusion_matrix

print("\nConfusion Matrix:\n", confusion_matrix(y_train, y_pred_train))

Confusion Matrix:
 [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

In [26]:
y=labelencoder.fit_transform(Y)
y

array([255, 297, 267, 158,  37, 290, 133, 306, 129,  55, 234, 309,  33,
       291, 294, 219, 170, 315, 331, 220, 122, 314,  71, 103, 271, 333,
       203,  77,  16, 184, 330, 200, 117, 223,  13, 293, 230,  63, 131,
        21,   8, 189, 277,  36,  38,  51, 317,  45,  32, 284,   5,  46,
       187, 145,  61, 140, 307,   4,  86,  75, 202, 154,   6, 208, 183,
        61, 227, 234, 328, 190, 252, 126,  88, 321, 117, 210, 286, 177,
        47, 239, 191, 165, 302,  46,   9, 208, 218, 304, 130, 188,  82,
        58,  49, 228, 204,  93, 253, 162, 318,  60,  35, 117,  79,  70,
        52,  90,   1, 210,  24, 232, 233, 132, 135, 110, 242, 209,  71,
       226, 169, 156, 141, 303, 142, 196, 229, 245, 298, 127,  64,  48,
       205, 126, 257, 172,  28, 125,  74, 127, 274, 316, 111, 128, 161,
         3, 237, 223,  31, 282, 168, 300, 280, 289, 174, 105, 143, 178,
       163, 272, 319, 243,  53,  15,  27,  96, 198,   2, 137, 137, 153,
       300, 191, 318, 235, 120,   0, 167,  94, 279, 287, 182,  62, 160,
        56,  81, 263, 268, 216, 111, 193, 313, 225, 135, 168, 326, 152,
        40,  34,  11,  26, 123,  91, 106,  34,   7, 221,  96,  65, 196,
       182,  17,  44, 247, 312, 199,  59,  10,  98,  43, 261, 285, 283,
       124, 163,  23,  34, 136, 183, 217,  85, 296,  73, 194, 325, 214,
       249,  89, 243, 259, 155,  30, 275, 311,  54, 185, 224, 264, 144,
        68,  84,  69, 240,  29, 201,  95, 258, 178,  41, 215,  24,  72,
       175,  97, 119, 181, 147,  80, 238, 101, 128,  67, 310,  50, 324,
       266, 151, 135, 146, 183, 151,  22,  14, 296, 180,  84, 148, 171,
       166, 142, 149, 222, 254, 134, 305, 299, 322,  42, 197,  18, 292,
       248, 211, 159,  78, 265, 308, 192,  57, 104, 241, 295, 256, 115,
       138, 244, 179, 121, 334, 122, 269, 148, 102, 165, 240, 276,  12,
       304,  55, 118,  20, 298,  66, 270,  99, 103, 173, 116,  74, 212,
       107, 301, 164, 157, 184, 109, 206,  58, 231, 142, 320, 243, 213,
       278, 329, 251,  79, 150,  25, 327,  39,  19, 223, 216,  76, 273,
       281, 128, 108, 332, 288, 273, 176, 236, 183,  93, 250, 186, 335,
       139, 113, 100, 260,  31,  63, 246, 323, 103,  81, 215, 195, 207,
        87, 112,  49,  92,  83, 320, 114, 159, 106, 262], dtype=int64)

In [27]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
num_trees = 200
#max_features = 3
kfold = KFold(n_splits=10, random_state=7, shuffle=True) #Bootstrap

model = RandomForestClassifier(n_estimators=num_trees,max_depth=5,  min_samples_leaf=5,max_features='sqrt')
results = cross_val_score(model, X, y, cv=kfold)
print(results.mean())

0.0

In [28]:
#AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

kfold = KFold(n_splits=10, random_state=7,shuffle=True) 
model1 = AdaBoostClassifier(n_estimators=100, random_state=7)
results = cross_val_score(model1, X, y, cv=kfold)
print(results.mean())

0.0

In [30]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [31]:
model = XGBClassifier(n_estimators=90,max_depth=3)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=90, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [32]:
y_pred_test = model.predict(X_test)
predictions = [round(value) for value in y_pred_test]
predictions

[213,
 13,
 91,
 20,
 208,
 73,
 92,
 162,
 48,
 16,
 79,
 79,
 123,
 48,
 40,
 182,
 44,
 226,
 79,
 58,
 40,
 37,
 226,
 111,
 12,
 164,
 196,
 191,
 130,
 237,
 48,
 150,
 126,
 237,
 79,
 157,
 97,
 91,
 145,
 92,
 150,
 157,
 157,
 77,
 130,
 48,
 73,
 62,
 58,
 91,
 169,
 232,
 130,
 198,
 106,
 237,
 49,
 98,
 118,
 157,
 97,
 19,
 23,
 93,
 125,
 231,
 20,
 73,
 164,
 203,
 68,
 171,
 180,
 187,
 83,
 92,
 243,
 200,
 172,
 14,
 103,
 108,
 170,
 198,
 146,
 157,
 23,
 135,
 135,
 169,
 99,
 233,
 226,
 92,
 208,
 73,
 125,
 111,
 172,
 123,
 173,
 83,
 169,
 146,
 159,
 198,
 207,
 197,
 79,
 111,
 91,
 83,
 111,
 237,
 73,
 184,
 48,
 131,
 243,
 83]

In [35]:
print(classification_report(predictions,y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         0
          18       0.00      0.00      0.00         0
          19       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         2
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         0
          23       0.00      0.00      0.00         2
          24       0.00      0.00      0.00         0
          25       0.00      0.00      0.00         0
          26       0.00      0.00      0.00         0
          27       0.00      0.00      0.00         0
          28       0.00      0.00      0.00         0
          29       0.00      0.00      0.00         0
          30       0.00      0.00      0.00         0
          31       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         0
          33       0.00      0.00      0.00         0
          34       0.00      0.00      0.00         0
          35       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         0
          37       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         0
          39       0.00      0.00      0.00         0
          40       0.00      0.00      0.00         2
          41       0.00      0.00      0.00         0
          42       0.00      0.00      0.00         0
          43       0.00      0.00      0.00         0
          44       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         0
          46       0.00      0.00      0.00         0
          47       0.00      0.00      0.00         0
          48       0.00      0.00      0.00         5
          49       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         0
          51       0.00      0.00      0.00         0
          52       0.00      0.00      0.00         0
          53       0.00      0.00      0.00         0
          54       0.00      0.00      0.00         0
          55       0.00      0.00      0.00         0
          56       0.00      0.00      0.00         0
          57       0.00      0.00      0.00         0
          58       0.00      0.00      0.00         2
          59       0.00      0.00      0.00         0
          60       0.00      0.00      0.00         0
          61       0.00      0.00      0.00         0
          62       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         0
          64       0.00      0.00      0.00         0
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         0
          67       0.00      0.00      0.00         0
          68       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         0
          70       0.00      0.00      0.00         0
          71       0.00      0.00      0.00         0
          72       0.00      0.00      0.00         0
          73       0.00      0.00      0.00         5
          74       0.00      0.00      0.00         0
          75       0.00      0.00      0.00         0
          76       0.00      0.00      0.00         0
          77       0.00      0.00      0.00         1
          78       0.00      0.00      0.00         0
          79       1.00      0.20      0.33         5
          80       0.00      0.00      0.00         0
          81       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         0
          83       0.00      0.00      0.00         4
          84       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         0
          86       0.00      0.00      0.00         0
          87       0.00      0.00      0.00         0
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         4
          92       0.00      0.00      0.00         4
          93       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         0
          96       0.00      0.00      0.00         0
          97       0.00      0.00      0.00         2
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         1
         100       0.00      0.00      0.00         0
         101       0.00      0.00      0.00         0
         102       0.00      0.00      0.00         0
         103       0.00      0.00      0.00         1
         104       0.00      0.00      0.00         0
         105       0.00      0.00      0.00         0
         106       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         0
         108       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         0
         110       0.00      0.00      0.00         0
         111       0.00      0.00      0.00         4
         112       0.00      0.00      0.00         0
         113       0.00      0.00      0.00         0
         118       0.00      0.00      0.00         1
         123       0.00      0.00      0.00         2
         125       0.00      0.00      0.00         2
         126       0.00      0.00      0.00         1
         130       0.00      0.00      0.00         3
         131       0.00      0.00      0.00         1
         135       0.00      0.00      0.00         2
         145       0.00      0.00      0.00         1
         146       0.00      0.00      0.00         2
         150       0.00      0.00      0.00         2
         157       0.00      0.00      0.00         5
         159       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         1
         164       0.00      0.00      0.00         2
         169       0.00      0.00      0.00         3
         170       0.00      0.00      0.00         1
         171       0.00      0.00      0.00         1
         172       0.00      0.00      0.00         2
         173       0.00      0.00      0.00         1
         180       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         184       0.00      0.00      0.00         1
         187       0.00      0.00      0.00         1
         191       0.00      0.00      0.00         1
         196       0.00      0.00      0.00         1
         197       0.00      0.00      0.00         1
         198       0.00      0.00      0.00         3
         200       0.00      0.00      0.00         1
         203       0.00      0.00      0.00         1
         207       0.00      0.00      0.00         1
         208       0.00      0.00      0.00         2
         213       0.00      0.00      0.00         1
         226       0.00      0.00      0.00         3
         231       0.00      0.00      0.00         1
         232       0.00      0.00      0.00         1
         233       0.00      0.00      0.00         1
         237       0.00      0.00      0.00         4
         243       0.00      0.00      0.00         2

    accuracy                           0.01       120
   macro avg       0.01      0.00      0.00       120
weighted avg       0.04      0.01      0.01       120

In [36]:
import lightgbm as lgb
d_train = lgb.Dataset(X_train, label=Y_train)

In [37]:
params = {}
params['learning_rate'] = 0.002, # 0.1,0.3
params['boosting_type'] = 'gbdt' # dart
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.5 
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10

In [38]:
params

{'learning_rate': (0.002,),
 'boosting_type': 'gbdt',
 'objective': 'binary',
 'metric': 'binary_logloss',
 'sub_feature': 0.5,
 'num_leaves': 10,
 'min_data': 50,
 'max_depth': 10}

In [39]:
clf = lgb.train(params, d_train, 1400)

[LightGBM] [Warning] Contains only one class
[LightGBM] [Info] Number of positive: 280, number of negative: 0
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000305 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 280, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=1.000000 -> initscore=34.539576
[LightGBM] [Info] Start training from score 34.539576
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [40]:
y_pred = clf.predict(X_test)

In [41]:
predictions = [round(value) for value in y_pred]

In [43]:
print(classification_report(predictions,y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.01      0.02       120
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         0
          17       0.00      0.00      0.00         0
          18       0.00      0.00      0.00         0
          19       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         0
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         0
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         0
          25       0.00      0.00      0.00         0
          26       0.00      0.00      0.00         0
          27       0.00      0.00      0.00         0
          28       0.00      0.00      0.00         0
          29       0.00      0.00      0.00         0
          30       0.00      0.00      0.00         0
          31       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         0
          33       0.00      0.00      0.00         0
          34       0.00      0.00      0.00         0
          35       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         0
          37       0.00      0.00      0.00         0
          38       0.00      0.00      0.00         0
          39       0.00      0.00      0.00         0
          40       0.00      0.00      0.00         0
          41       0.00      0.00      0.00         0
          42       0.00      0.00      0.00         0
          43       0.00      0.00      0.00         0
          44       0.00      0.00      0.00         0
          45       0.00      0.00      0.00         0
          46       0.00      0.00      0.00         0
          47       0.00      0.00      0.00         0
          48       0.00      0.00      0.00         0
          49       0.00      0.00      0.00         0
          50       0.00      0.00      0.00         0
          51       0.00      0.00      0.00         0
          52       0.00      0.00      0.00         0
          53       0.00      0.00      0.00         0
          54       0.00      0.00      0.00         0
          55       0.00      0.00      0.00         0
          56       0.00      0.00      0.00         0
          57       0.00      0.00      0.00         0
          58       0.00      0.00      0.00         0
          59       0.00      0.00      0.00         0
          60       0.00      0.00      0.00         0
          61       0.00      0.00      0.00         0
          62       0.00      0.00      0.00         0
          63       0.00      0.00      0.00         0
          64       0.00      0.00      0.00         0
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         0
          67       0.00      0.00      0.00         0
          68       0.00      0.00      0.00         0
          69       0.00      0.00      0.00         0
          70       0.00      0.00      0.00         0
          71       0.00      0.00      0.00         0
          72       0.00      0.00      0.00         0
          73       0.00      0.00      0.00         0
          74       0.00      0.00      0.00         0
          75       0.00      0.00      0.00         0
          76       0.00      0.00      0.00         0
          77       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         0
          79       0.00      0.00      0.00         0
          80       0.00      0.00      0.00         0
          81       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         0
          83       0.00      0.00      0.00         0
          84       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         0
          86       0.00      0.00      0.00         0
          87       0.00      0.00      0.00         0
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         0
          92       0.00      0.00      0.00         0
          93       0.00      0.00      0.00         0
          94       0.00      0.00      0.00         0
          95       0.00      0.00      0.00         0
          96       0.00      0.00      0.00         0
          97       0.00      0.00      0.00         0
          98       0.00      0.00      0.00         0
          99       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         0
         101       0.00      0.00      0.00         0
         102       0.00      0.00      0.00         0
         103       0.00      0.00      0.00         0
         104       0.00      0.00      0.00         0
         105       0.00      0.00      0.00         0
         106       0.00      0.00      0.00         0
         107       0.00      0.00      0.00         0
         108       0.00      0.00      0.00         0
         109       0.00      0.00      0.00         0
         110       0.00      0.00      0.00         0
         111       0.00      0.00      0.00         0
         112       0.00      0.00      0.00         0
         113       0.00      0.00      0.00         0

    accuracy                           0.01       120
   macro avg       0.01      0.00      0.00       120
weighted avg       1.00      0.01      0.02       120