In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy

In [2]:
df= pd.read_csv(r'C:\Users\SHYAM SASHANK\OneDrive\Desktop\Data_Science\Assginment_CSV\gas_turbines.csv')

In [3]:
df.head()

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,114.70,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,114.72,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,114.71,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,114.72,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,114.72,10.612,3.2484,82.311

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   TEY     15039 non-null  float64
 8   CDP     15039 non-null  float64
 9   CO      15039 non-null  float64
 10  NOX     15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB

In [5]:
X=df.drop(columns="TEY")
X.head()

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,10.612,3.2484,82.311

In [6]:
Y=df[["TEY"]]
Y

          TEY
0      114.70
1      114.72
2      114.71
3      114.72
4      114.72
...       ...
15034  111.61
15035  111.78
15036  110.19
15037  110.74
15038  111.58

[15039 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, random_state=30, test_size=0.4)

In [14]:
X_train

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX
5410,17.1680,1015.3,83.152,3.5539,20.413,1061.5,549.93,10.708,4.43190,67.094
12396,26.5380,1007.0,72.606,4.2568,27.723,1096.2,545.73,12.706,0.34727,61.440
2392,21.1290,1003.0,75.061,4.2875,20.223,1057.8,549.84,10.630,2.80340,60.323
5059,22.2540,1015.3,71.750,4.2983,25.581,1091.6,550.20,12.136,2.52750,70.452
10313,18.3070,1012.9,79.324,4.5052,31.645,1100.1,533.10,13.673,1.30270,63.034
...,...,...,...,...,...,...,...,...,...,...
13452,23.1540,1014.0,71.004,4.4694,28.885,1100.4,543.40,12.992,1.14260,61.138
500,2.8258,1009.1,81.773,5.0467,29.647,1099.9,541.14,13.210,0.16464,79.371
12077,31.3320,1014.2,49.275,4.4837,29.665,1099.5,541.85,13.211,0.87442,58.806
4517,28.5630,1009.9,64.346,4.3587,26.438,1094.3,549.97,12.290,0.48279,62.532
5925,21.1160,1012.1,86.218,4.4351,25.283,1089.3,550.16,12.047,2.22070,60.612

In [15]:
X_test

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX
3390,29.267,1012.4,43.795,4.2298,26.061,1093.2,550.06,12.206,1.6412,71.559
1194,11.523,1024.4,88.089,4.3647,22.037,1069.2,548.48,11.221,2.4251,76.116
13890,15.226,1019.0,84.659,3.8886,24.045,1087.1,549.91,11.938,1.7065,75.188
5570,27.382,1016.1,61.555,4.4794,26.085,1093.7,550.04,12.337,1.3872,66.656
6190,19.101,1008.6,83.062,4.3643,25.352,1089.7,550.16,12.030,2.4755,68.209
...,...,...,...,...,...,...,...,...,...,...
9970,13.445,1009.8,99.129,4.7876,32.125,1100.1,531.40,13.845,1.0294,56.599
14295,10.523,1023.1,63.667,5.1533,32.943,1099.8,527.67,14.115,1.1203,66.968
6496,16.306,1012.5,74.317,4.2502,24.946,1089.0,549.93,11.945,1.0386,67.718
12411,22.690,1006.1,76.467,3.0504,20.189,1060.0,549.93,10.609,1.7930,54.197
10681,20.422,1009.0,82.110,3.6212,24.754,1087.7,549.97,11.966,0.8024,61.607

In [16]:
Y_train

          TEY
5410   114.21
12396  139.18
2392   111.47
5059   133.73
10313  156.43
...       ...
13452  146.73
500    156.47
12077  146.47
4517   134.75
5925   133.64

[9023 rows x 1 columns]

In [17]:
Y_test

          TEY
3390   132.78
1194   122.78
13890  133.78
5570   133.76
6190   134.26
...       ...
9970   159.21
14295  162.25
6496   134.91
12411  111.77
10681  132.88

[6016 rows x 1 columns]

In [18]:
# create model
model = Sequential()
model.add(Dense(20, input_dim=10,  activation='relu')) #1st layer
model.add(Dense(10,  activation='relu')) #2nd layer
model.add(Dense(10,  activation='relu')) #3nd layer 
model.add(Dense(1, activation='sigmoid')) #4th layer or output layer

In [19]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 20)                220

 dense_5 (Dense)             (None, 10)                210

 dense_6 (Dense)             (None, 10)                110

 dense_7 (Dense)             (None, 1)                 11

=================================================================
Total params: 551
Trainable params: 551
Non-trainable params: 0
_________________________________________________________________

In [21]:
gas=model.fit(X_train, Y_train, validation_data=(X_test,Y_test), epochs=100, batch_size=20)

Epoch 1/100
452/452 [==============================] - 2s 3ms/step - loss: -6885923.5000 - accuracy: 0.0000e+00 - val_loss: -35653208.0000 - val_accuracy: 0.0000e+00
Epoch 2/100
452/452 [==============================] - 1s 3ms/step - loss: -226946592.0000 - accuracy: 0.0000e+00 - val_loss: -585201920.0000 - val_accuracy: 0.0000e+00
Epoch 3/100
452/452 [==============================] - 1s 3ms/step - loss: -1464496128.0000 - accuracy: 0.0000e+00 - val_loss: -2721291008.0000 - val_accuracy: 0.0000e+00
Epoch 4/100
452/452 [==============================] - 1s 3ms/step - loss: -4906326016.0000 - accuracy: 0.0000e+00 - val_loss: -7695948288.0000 - val_accuracy: 0.0000e+00
Epoch 5/100
452/452 [==============================] - 1s 3ms/step - loss: -11820693504.0000 - accuracy: 0.0000e+00 - val_loss: -16772115456.0000 - val_accuracy: 0.0000e+00
Epoch 6/100
452/452 [==============================] - 1s 3ms/step - loss: -23440961536.0000 - accuracy: 0.0000e+00 - val_loss: -31156416512.0000 - val_accuracy: 0.0000e+00
Epoch 7/100
452/452 [==============================] - 1s 3ms/step - loss: -40934322176.0000 - accuracy: 0.0000e+00 - val_loss: -51982524416.0000 - val_accuracy: 0.0000e+00
Epoch 8/100
452/452 [==============================] - 1s 3ms/step - loss: -65446658048.0000 - accuracy: 0.0000e+00 - val_loss: -80406683648.0000 - val_accuracy: 0.0000e+00
Epoch 9/100
452/452 [==============================] - 1s 3ms/step - loss: -98110439424.0000 - accuracy: 0.0000e+00 - val_loss: -117540732928.0000 - val_accuracy: 0.0000e+00
Epoch 10/100
452/452 [==============================] - 1s 3ms/step - loss: -140055461888.0000 - accuracy: 0.0000e+00 - val_loss: -164533272576.0000 - val_accuracy: 0.0000e+00
Epoch 11/100
452/452 [==============================] - 1s 3ms/step - loss: -192441548800.0000 - accuracy: 0.0000e+00 - val_loss: -222558240768.0000 - val_accuracy: 0.0000e+00
Epoch 12/100
452/452 [==============================] - 1s 3ms/step - loss: -256403636224.0000 - accuracy: 0.0000e+00 - val_loss: -292752523264.0000 - val_accuracy: 0.0000e+00
Epoch 13/100
452/452 [==============================] - 1s 3ms/step - loss: -333180338176.0000 - accuracy: 0.0000e+00 - val_loss: -376420499456.0000 - val_accuracy: 0.0000e+00
Epoch 14/100
452/452 [==============================] - 1s 3ms/step - loss: -424034828288.0000 - accuracy: 0.0000e+00 - val_loss: -474760019968.0000 - val_accuracy: 0.0000e+00
Epoch 15/100
452/452 [==============================] - 1s 3ms/step - loss: -530250498048.0000 - accuracy: 0.0000e+00 - val_loss: -589164314624.0000 - val_accuracy: 0.0000e+00
Epoch 16/100
452/452 [==============================] - 1s 3ms/step - loss: -653127319552.0000 - accuracy: 0.0000e+00 - val_loss: -720884596736.0000 - val_accuracy: 0.0000e+00
Epoch 17/100
452/452 [==============================] - 1s 3ms/step - loss: -794091585536.0000 - accuracy: 0.0000e+00 - val_loss: -871409385472.0000 - val_accuracy: 0.0000e+00
Epoch 18/100
452/452 [==============================] - 1s 3ms/step - loss: -954500907008.0000 - accuracy: 0.0000e+00 - val_loss: -1042100191232.0000 - val_accuracy: 0.0000e+00
Epoch 19/100
452/452 [==============================] - 1s 3ms/step - loss: -1135843737600.0000 - accuracy: 0.0000e+00 - val_loss: -1234512642048.0000 - val_accuracy: 0.0000e+00
Epoch 20/100
452/452 [==============================] - 1s 3ms/step - loss: -1339541291008.0000 - accuracy: 0.0000e+00 - val_loss: -1449993699328.0000 - val_accuracy: 0.0000e+00
Epoch 21/100
452/452 [==============================] - 1s 3ms/step - loss: -1567317426176.0000 - accuracy: 0.0000e+00 - val_loss: -1690402160640.0000 - val_accuracy: 0.0000e+00
Epoch 22/100
452/452 [==============================] - 1s 3ms/step - loss: -1820543680512.0000 - accuracy: 0.0000e+00 - val_loss: -1956956602368.0000 - val_accuracy: 0.0000e+00
Epoch 23/100
452/452 [==============================] - 1s 3ms/step - loss: -2100899479552.0000 - accuracy: 0.0000e+00 - val_loss: -2251557437440.0000 - val_accuracy: 0.0000e+00
Epoch 24/100
452/452 [==============================] - 1s 3ms/step - loss: -2410017456128.0000 - accuracy: 0.0000e+00 - val_loss: -2575797583872.0000 - val_accuracy: 0.0000e+00
Epoch 25/100
452/452 [==============================] - 1s 3ms/step - loss: -2749701816320.0000 - accuracy: 0.0000e+00 - val_loss: -2931396706304.0000 - val_accuracy: 0.0000e+00
Epoch 26/100
452/452 [==============================] - 1s 3ms/step - loss: -3121661607936.0000 - accuracy: 0.0000e+00 - val_loss: -3320164646912.0000 - val_accuracy: 0.0000e+00
Epoch 27/100
452/452 [==============================] - 1s 3ms/step - loss: -3527698546688.0000 - accuracy: 0.0000e+00 - val_loss: -3743980716032.0000 - val_accuracy: 0.0000e+00
Epoch 28/100
452/452 [==============================] - 1s 3ms/step - loss: -3969506869248.0000 - accuracy: 0.0000e+00 - val_loss: -4204405719040.0000 - val_accuracy: 0.0000e+00
Epoch 29/100
452/452 [==============================] - 1s 3ms/step - loss: -4448828522496.0000 - accuracy: 0.0000e+00 - val_loss: -4703338364928.0000 - val_accuracy: 0.0000e+00
Epoch 30/100
452/452 [==============================] - 1s 3ms/step - loss: -4967825408000.0000 - accuracy: 0.0000e+00 - val_loss: -5242931904512.0000 - val_accuracy: 0.0000e+00
Epoch 31/100
452/452 [==============================] - 1s 2ms/step - loss: -5528241045504.0000 - accuracy: 0.0000e+00 - val_loss: -5824996442112.0000 - val_accuracy: 0.0000e+00
Epoch 32/100
452/452 [==============================] - 1s 2ms/step - loss: -6132049379328.0000 - accuracy: 0.0000e+00 - val_loss: -6451418365952.0000 - val_accuracy: 0.0000e+00
Epoch 33/100
452/452 [==============================] - 1s 3ms/step - loss: -6781255811072.0000 - accuracy: 0.0000e+00 - val_loss: -7124079345664.0000 - val_accuracy: 0.0000e+00
Epoch 34/100
452/452 [==============================] - 1s 3ms/step - loss: -7478182936576.0000 - accuracy: 0.0000e+00 - val_loss: -7845775933440.0000 - val_accuracy: 0.0000e+00
Epoch 35/100
452/452 [==============================] - 1s 3ms/step - loss: -8224673628160.0000 - accuracy: 0.0000e+00 - val_loss: -8617993437184.0000 - val_accuracy: 0.0000e+00
Epoch 36/100
452/452 [==============================] - 1s 3ms/step - loss: -9022622138368.0000 - accuracy: 0.0000e+00 - val_loss: -9442777104384.0000 - val_accuracy: 0.0000e+00
Epoch 37/100
452/452 [==============================] - 1s 3ms/step - loss: -9874590138368.0000 - accuracy: 0.0000e+00 - val_loss: -10322595282944.0000 - val_accuracy: 0.0000e+00
Epoch 38/100
452/452 [==============================] - 1s 3ms/step - loss: -10782688411648.0000 - accuracy: 0.0000e+00 - val_loss: -11259842920448.0000 - val_accuracy: 0.0000e+00
Epoch 39/100
452/452 [==============================] - 1s 3ms/step - loss: -11749205999616.0000 - accuracy: 0.0000e+00 - val_loss: -12256470368256.0000 - val_accuracy: 0.0000e+00
Epoch 40/100
452/452 [==============================] - 1s 3ms/step - loss: -12776200208384.0000 - accuracy: 0.0000e+00 - val_loss: -13314995257344.0000 - val_accuracy: 0.0000e+00
Epoch 41/100
452/452 [==============================] - 1s 3ms/step - loss: -13866153017344.0000 - accuracy: 0.0000e+00 - val_loss: -14437323898880.0000 - val_accuracy: 0.0000e+00
Epoch 42/100
452/452 [==============================] - 1s 3ms/step - loss: -15021214007296.0000 - accuracy: 0.0000e+00 - val_loss: -15626114433024.0000 - val_accuracy: 0.0000e+00
Epoch 43/100
452/452 [==============================] - 1s 3ms/step - loss: -16244027686912.0000 - accuracy: 0.0000e+00 - val_loss: -16883980959744.0000 - val_accuracy: 0.0000e+00
Epoch 44/100
452/452 [==============================] - 1s 2ms/step - loss: -17536377683968.0000 - accuracy: 0.0000e+00 - val_loss: -18212477468672.0000 - val_accuracy: 0.0000e+00
Epoch 45/100
452/452 [==============================] - 1s 3ms/step - loss: -18901568061440.0000 - accuracy: 0.0000e+00 - val_loss: -19615413436416.0000 - val_accuracy: 0.0000e+00
Epoch 46/100
452/452 [==============================] - 1s 3ms/step - loss: -20342080798720.0000 - accuracy: 0.0000e+00 - val_loss: -21094515867648.0000 - val_accuracy: 0.0000e+00
Epoch 47/100

452/452 [==============================] - 1s 3ms/step - loss: -21859743563776.0000 - accuracy: 0.0000e+00 - val_loss: -22652299247616.0000 - val_accuracy: 0.0000e+00
Epoch 48/100
452/452 [==============================] - 1s 3ms/step - loss: -23457494466560.0000 - accuracy: 0.0000e+00 - val_loss: -24291227729920.0000 - val_accuracy: 0.0000e+00
Epoch 49/100
452/452 [==============================] - 1s 3ms/step - loss: -25138135302144.0000 - accuracy: 0.0000e+00 - val_loss: -26014426071040.0000 - val_accuracy: 0.0000e+00
Epoch 50/100
452/452 [==============================] - 1s 3ms/step - loss: -26904088281088.0000 - accuracy: 0.0000e+00 - val_loss: -27824614277120.0000 - val_accuracy: 0.0000e+00
Epoch 51/100
452/452 [==============================] - 1s 3ms/step - loss: -28757916123136.0000 - accuracy: 0.0000e+00 - val_loss: -29723950317568.0000 - val_accuracy: 0.0000e+00
Epoch 52/100
452/452 [==============================] - 1s 3ms/step - loss: -30703020408832.0000 - accuracy: 0.0000e+00 - val_loss: -31715923853312.0000 - val_accuracy: 0.0000e+00
Epoch 53/100
452/452 [==============================] - 2s 3ms/step - loss: -32741529747456.0000 - accuracy: 0.0000e+00 - val_loss: -33802476847104.0000 - val_accuracy: 0.0000e+00
Epoch 54/100
452/452 [==============================] - 2s 4ms/step - loss: -34876034121728.0000 - accuracy: 0.0000e+00 - val_loss: -35986784387072.0000 - val_accuracy: 0.0000e+00
Epoch 55/100
452/452 [==============================] - 1s 3ms/step - loss: -37109838643200.0000 - accuracy: 0.0000e+00 - val_loss: -38271866372096.0000 - val_accuracy: 0.0000e+00
Epoch 56/100
452/452 [==============================] - 1s 3ms/step - loss: -39446682533888.0000 - accuracy: 0.0000e+00 - val_loss: -40660799324160.0000 - val_accuracy: 0.0000e+00
Epoch 57/100
452/452 [==============================] - 1s 3ms/step - loss: -41887704547328.0000 - accuracy: 0.0000e+00 - val_loss: -43156166934528.0000 - val_accuracy: 0.0000e+00
Epoch 58/100
452/452 [==============================] - 1s 3ms/step - loss: -44435320602624.0000 - accuracy: 0.0000e+00 - val_loss: -45759521095680.0000 - val_accuracy: 0.0000e+00
Epoch 59/100
452/452 [==============================] - 1s 3ms/step - loss: -47094639362048.0000 - accuracy: 0.0000e+00 - val_loss: -48475618148352.0000 - val_accuracy: 0.0000e+00
Epoch 60/100
452/452 [==============================] - 1s 3ms/step - loss: -49868869468160.0000 - accuracy: 0.0000e+00 - val_loss: -51308958580736.0000 - val_accuracy: 0.0000e+00
Epoch 61/100
452/452 [==============================] - 1s 3ms/step - loss: -52759583784960.0000 - accuracy: 0.0000e+00 - val_loss: -54259525615616.0000 - val_accuracy: 0.0000e+00
Epoch 62/100
452/452 [==============================] - 1s 3ms/step - loss: -55770972422144.0000 - accuracy: 0.0000e+00 - val_loss: -57332771848192.0000 - val_accuracy: 0.0000e+00
Epoch 63/100
452/452 [==============================] - 1s 3ms/step - loss: -58905237389312.0000 - accuracy: 0.0000e+00 - val_loss: -60530664407040.0000 - val_accuracy: 0.0000e+00
Epoch 64/100
452/452 [==============================] - 1s 3ms/step - loss: -62165000126464.0000 - accuracy: 0.0000e+00 - val_loss: -63855036203008.0000 - val_accuracy: 0.0000e+00
Epoch 65/100
452/452 [==============================] - 1s 3ms/step - loss: -65554224250880.0000 - accuracy: 0.0000e+00 - val_loss: -67310681325568.0000 - val_accuracy: 0.0000e+00
Epoch 66/100
452/452 [==============================] - 1s 3ms/step - loss: -69076143570944.0000 - accuracy: 0.0000e+00 - val_loss: -70902184148992.0000 - val_accuracy: 0.0000e+00
Epoch 67/100
452/452 [==============================] - 1s 3ms/step - loss: -72734851727360.0000 - accuracy: 0.0000e+00 - val_loss: -74629972492288.0000 - val_accuracy: 0.0000e+00
Epoch 68/100
452/452 [==============================] - 1s 3ms/step - loss: -76532643004416.0000 - accuracy: 0.0000e+00 - val_loss: -78499956129792.0000 - val_accuracy: 0.0000e+00
Epoch 69/100
452/452 [==============================] - 1s 3ms/step - loss: -80473963364352.0000 - accuracy: 0.0000e+00 - val_loss: -82514366431232.0000 - val_accuracy: 0.0000e+00
Epoch 70/100
452/452 [==============================] - 1s 3ms/step - loss: -84561639768064.0000 - accuracy: 0.0000e+00 - val_loss: -86676995047424.0000 - val_accuracy: 0.0000e+00
Epoch 71/100
452/452 [==============================] - 1s 3ms/step - loss: -88798381735936.0000 - accuracy: 0.0000e+00 - val_loss: -90991180644352.0000 - val_accuracy: 0.0000e+00
Epoch 72/100
452/452 [==============================] - 1s 3ms/step - loss: -93187787980800.0000 - accuracy: 0.0000e+00 - val_loss: -95458911322112.0000 - val_accuracy: 0.0000e+00
Epoch 73/100
452/452 [==============================] - 1s 3ms/step - loss: -97733281054720.0000 - accuracy: 0.0000e+00 - val_loss: -100085530624000.0000 - val_accuracy: 0.0000e+00
Epoch 74/100
452/452 [==============================] - 1s 3ms/step - loss: -102438652608512.0000 - accuracy: 0.0000e+00 - val_loss: -104873664184320.0000 - val_accuracy: 0.0000e+00
Epoch 75/100
452/452 [==============================] - 1s 3ms/step - loss: -107308415713280.0000 - accuracy: 0.0000e+00 - val_loss: -109827338534912.0000 - val_accuracy: 0.0000e+00
Epoch 76/100
452/452 [==============================] - 1s 3ms/step - loss: -112345019842560.0000 - accuracy: 0.0000e+00 - val_loss: -114949061869568.0000 - val_accuracy: 0.0000e+00
Epoch 77/100
452/452 [==============================] - 1s 3ms/step - loss: -117551778496512.0000 - accuracy: 0.0000e+00 - val_loss: -120244613939200.0000 - val_accuracy: 0.0000e+00
Epoch 78/100
452/452 [==============================] - 1s 3ms/step - loss: -122933540290560.0000 - accuracy: 0.0000e+00 - val_loss: -125715177537536.0000 - val_accuracy: 0.0000e+00
Epoch 79/100
452/452 [==============================] - 1s 3ms/step - loss: -128495246114816.0000 - accuracy: 0.0000e+00 - val_loss: -131367849426944.0000 - val_accuracy: 0.0000e+00
Epoch 80/100
452/452 [==============================] - 1s 3ms/step - loss: -134236610756608.0000 - accuracy: 0.0000e+00 - val_loss: -137203770458112.0000 - val_accuracy: 0.0000e+00
Epoch 81/100
452/452 [==============================] - 1s 3ms/step - loss: -140164034723840.0000 - accuracy: 0.0000e+00 - val_loss: -143227545976832.0000 - val_accuracy: 0.0000e+00
Epoch 82/100
452/452 [==============================] - 1s 3ms/step - loss: -146282106585088.0000 - accuracy: 0.0000e+00 - val_loss: -149441155694592.0000 - val_accuracy: 0.0000e+00
Epoch 83/100
452/452 [==============================] - 1s 3ms/step - loss: -152592957046784.0000 - accuracy: 0.0000e+00 - val_loss: -155852451348480.0000 - val_accuracy: 0.0000e+00
Epoch 84/100
452/452 [==============================] - 1s 3ms/step - loss: -159103221497856.0000 - accuracy: 0.0000e+00 - val_loss: -162464704495616.0000 - val_accuracy: 0.0000e+00
Epoch 85/100
452/452 [==============================] - 1s 3ms/step - loss: -165812161740800.0000 - accuracy: 0.0000e+00 - val_loss: -169276690399232.0000 - val_accuracy: 0.0000e+00
Epoch 86/100
452/452 [==============================] - 1s 3ms/step - loss: -172727981834240.0000 - accuracy: 0.0000e+00 - val_loss: -176298492166144.0000 - val_accuracy: 0.0000e+00
Epoch 87/100
452/452 [==============================] - 1s 3ms/step - loss: -179853265469440.0000 - accuracy: 0.0000e+00 - val_loss: -183531451973632.0000 - val_accuracy: 0.0000e+00
Epoch 88/100
452/452 [==============================] - 1s 3ms/step - loss: -187190730555392.0000 - accuracy: 0.0000e+00 - val_loss: -190979462135808.0000 - val_accuracy: 0.0000e+00
Epoch 89/100
452/452 [==============================] - 1s 3ms/step - loss: -194747775844352.0000 - accuracy: 0.0000e+00 - val_loss: -198647438376960.0000 - val_accuracy: 0.0000e+00
Epoch 90/100
452/452 [==============================] - 1s 3ms/step - loss: -202524736880640.0000 - accuracy: 0.0000e+00 - val_loss: -206539424006144.0000 - val_accuracy: 0.0000e+00
Epoch 91/100
452/452 [==============================] - 1s 3ms/step - loss: -210529163411456.0000 - accuracy: 0.0000e+00 - val_loss: -214658153709568.0000 - val_accuracy: 0.0000e+00
Epoch 92/100

452/452 [==============================] - 1s 3ms/step - loss: -218760048803840.0000 - accuracy: 0.0000e+00 - val_loss: -223008140558336.0000 - val_accuracy: 0.0000e+00
Epoch 93/100
452/452 [==============================] - 1s 3ms/step - loss: -227227090288640.0000 - accuracy: 0.0000e+00 - val_loss: -231594484826112.0000 - val_accuracy: 0.0000e+00
Epoch 94/100
452/452 [==============================] - 1s 3ms/step - loss: -235930455638016.0000 - accuracy: 0.0000e+00 - val_loss: -240420827168768.0000 - val_accuracy: 0.0000e+00
Epoch 95/100
452/452 [==============================] - 1s 3ms/step - loss: -244877862371328.0000 - accuracy: 0.0000e+00 - val_loss: -249493442265088.0000 - val_accuracy: 0.0000e+00
Epoch 96/100
452/452 [==============================] - 1s 3ms/step - loss: -254071994843136.0000 - accuracy: 0.0000e+00 - val_loss: -258812917317632.0000 - val_accuracy: 0.0000e+00
Epoch 97/100
452/452 [==============================] - 1s 3ms/step - loss: -263517835886592.0000 - accuracy: 0.0000e+00 - val_loss: -268390107185152.0000 - val_accuracy: 0.0000e+00
Epoch 98/100
452/452 [==============================] - 1s 3ms/step - loss: -273220905205760.0000 - accuracy: 0.0000e+00 - val_loss: -278223317368832.0000 - val_accuracy: 0.0000e+00
Epoch 99/100
452/452 [==============================] - 1s 3ms/step - loss: -283183937486848.0000 - accuracy: 0.0000e+00 - val_loss: -288320315719680.0000 - val_accuracy: 0.0000e+00
Epoch 100/100
452/452 [==============================] - 1s 3ms/step - loss: -293409717747712.0000 - accuracy: 0.0000e+00 - val_loss: -298682226311168.0000 - val_accuracy: 0.0000e+00

In [22]:
scores = model.evaluate(X, Y)
print(model.metrics_names)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print(scores)

470/470 [==============================] - 1s 1ms/step - loss: -298652866183168.0000 - accuracy: 0.0000e+00
['loss', 'accuracy']
accuracy: 0.00%
[-298652866183168.0, 0.0]

In [24]:
loss, accuracy = model.evaluate(X_test, Y_test)
print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')

188/188 [==============================] - 0s 2ms/step - loss: -298682159202304.0000 - accuracy: 0.0000e+00
Test Loss: -298682159202304.0000, Test Accuracy: 0.0000

In [25]:
y_pred_train=model.predict(X_train)
y_pred_train

282/282 [==============================] - 1s 1ms/step

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [27]:
y_pred_test= model.predict(X_test)
y_pred_test

188/188 [==============================] - 0s 2ms/step

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)