In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r'C:\Users\SHYAM SASHANK\OneDrive\Desktop\Data_Science\Assginment_CSV\banks.csv')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [4]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [5]:
x=df.drop(columns=['y','job','marital','education','default','housing','loan','contact','month','poutcome'])
x.head()

   age  balance  day  duration  campaign  pdays  previous
0   58     2143    5       261         1     -1         0
1   44       29    5       151         1     -1         0
2   33        2    5        76         1     -1         0
3   47     1506    5        92         1     -1         0
4   33        1    5       198         1     -1         0

In [6]:
x.tail()

       age  balance  day  duration  campaign  pdays  previous
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr=LogisticRegression()

In [9]:
y=df[['y']]
y

         y
0       no
1       no
2       no
3       no
4       no
...    ...
45206  yes
45207  yes
45208  yes
45209   no
45210   no

[45211 rows x 1 columns]

In [64]:
y1=pd.get_dummies(y)
y1

       y_no  y_yes
0         1      0
1         1      0
2         1      0
3         1      0
4         1      0
...     ...    ...
45206     0      1
45207     0      1
45208     0      1
45209     1      0
45210     1      0

[45211 rows x 2 columns]

In [41]:
lr.fit(x,y)

C:\Users\SHYAM SASHANK\anaconda3\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SHYAM SASHANK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [42]:
predict=lr.predict(x)
predict

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [65]:
p1=pd.get_dummies(predict)
p1

       no  yes
0       1    0
1       1    0
2       1    0
3       1    0
4       1    0
...    ..  ...
45206   1    0
45207   1    0
45208   1    0
45209   1    0
45210   1    0

[45211 rows x 2 columns]

In [43]:
a=pd.DataFrame(predict)

In [44]:
df[['LR_Predict']]=a
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,LR_Predict,LR_Pred2
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,no,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,no,yes
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,no,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,no,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes,no,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes,no,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes,no,NaN
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no,no,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no,no,NaN

# #Method 2

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.4)

In [47]:
x_train

       age  balance  day  duration  campaign  pdays  previous
25490   45       38   19       159         1    188         2
20631   34      520   12      1307         4     -1         0
3400    30     -256   15        51         5     -1         0
17277   48      917   28       103         5     -1         0
24790   30       33   18        36         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
30403   35      995    5        39         1     -1         0
21243   35      750   18       233        12     -1         0
42613   35      323   11       261         2     -1         0
43567   70      616   27       149         2    182         1
2732    46       57   14       194         4     -1         0

[27126 rows x 7 columns]

In [48]:
x_test

       age  balance  day  duration  campaign  pdays  previous
14001   37     1403   10        91        15     -1         0
32046   36     -253   14      1073         1     -1         0
13318   47     -406    8       243         5     -1         0
42991   57      501   11       105         7    188         2
14237   33     -406   14       332         2     -1         0
...    ...      ...  ...       ...       ...    ...       ...
17247   28      111   28       230         2     -1         0
13270   38        0    8       452         3     -1         0
26058   37      510   19        67         2     90         6
14276   33      179   14       244         7     -1         0
28896   28       12   30        73         3    256         3

[18085 rows x 7 columns]

In [49]:
y_train

         y
25490   no
20631  yes
3400    no
17277   no
24790   no
...    ...
30403   no
21243   no
42613  yes
43567   no
2732    no

[27126 rows x 1 columns]

In [50]:
y_test

         y
14001   no
32046  yes
13318   no
42991   no
14237   no
...    ...
17247   no
13270   no
26058   no
14276   no
28896   no

[18085 rows x 1 columns]

In [51]:
lr.fit(x_train,y_train)

C:\Users\SHYAM SASHANK\anaconda3\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SHYAM SASHANK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [52]:
y_pred=lr.predict(x_train)

In [53]:
y_pred

array(['no', 'yes', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [54]:
y_pred_test=lr.predict(x_test)

In [55]:
y_pred_test

array(['no', 'yes', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [56]:
a1=pd.DataFrame(y_pred_test)
a1

         0
0       no
1      yes
2       no
3       no
4       no
...    ...
18080   no
18081   no
18082   no
18083   no
18084   no

[18085 rows x 1 columns]

In [57]:
y1=pd.DataFrame(y_pred)

In [58]:
y1

         0
0       no
1      yes
2       no
3       no
4       no
...    ...
27121   no
27122   no
27123   no
27124   no
27125   no

[27126 rows x 1 columns]

In [59]:
df[['LR_Pred2']]=y1
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,LR_Predict,LR_Pred2
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,no,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,no,yes
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,no,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,no,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes,no,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes,no,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes,no,NaN
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no,no,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no,no,NaN

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y,predict)
print (confusion_matrix)

[[39291   631]
 [ 4442   847]]

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y,predict))

              precision    recall  f1-score   support

          no       0.90      0.98      0.94     39922
         yes       0.57      0.16      0.25      5289

    accuracy                           0.89     45211
   macro avg       0.74      0.57      0.59     45211
weighted avg       0.86      0.89      0.86     45211

In [62]:
lr.predict_proba (x)[:,1]

array([0.08924362, 0.10391982, 0.12918551, ..., 0.23294333, 0.05585477,
       0.23049723])

In [70]:
# ROC Graph

from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

fpr, tpr, thresholds = roc_curve(y1, lr.predict_proba (x)[:,1])

auc = roc_auc_score(y1, p1)

import matplotlib.pyplot as plt
plt.plot(fpr, tpr, color='red', label='logit model ( area  = %0.2f)'%auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate or [1 - True Negative Rate]')
plt.ylabel('True Positive Rate')
plt.legend()
plt.show()

ValueError: multilabel-indicator format is not supported